apiVersion: v1
kind: Secret
metadata:
  name: {{ include "quantzen.fullname" . }}
type: Opaque
stringData:
  solvegio-api-key: {{ .Values.env.solvegioAPIKey | quote }}
  webhook-secret: {{ .Values.env.webhookSecret | quote }}
