apiVersion: v1
kind: Service
metadata:
  name: {{ include "quantzen.fullname" . }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "quantzen.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
  type: {{ .Values.service.type }}
