package main

import(
  "bytes";"context";"crypto/hmac";"crypto/sha256";"encoding/base64";"encoding/hex";"encoding/json";"fmt";"io";"log";"net/http";"net/http/httptest";"path";"strings";"sync/atomic";"time"
  "github.com/metadogeunity/solvegio-QuantZen/internal/audit"
  "github.com/metadogeunity/solvegio-QuantZen/internal/canonical"
  "github.com/metadogeunity/solvegio-QuantZen/internal/config"
  qzcrypto "github.com/metadogeunity/solvegio-QuantZen/internal/crypto"
  "github.com/metadogeunity/solvegio-QuantZen/internal/httpx"
  "github.com/metadogeunity/solvegio-QuantZen/internal/protocol"
  "github.com/metadogeunity/solvegio-QuantZen/internal/replay"
  "github.com/metadogeunity/solvegio-QuantZen/internal/solvegio"
  "github.com/metadogeunity/solvegio-QuantZen/internal/store"
  "github.com/metadogeunity/solvegio-QuantZen/internal/trust"
  "github.com/metadogeunity/solvegio-QuantZen/internal/webhook"
)

type App struct{cfg config.Config;audit *audit.Log;trust *trust.Registry;keys *qzcrypto.KeyStore;replay replay.Store;solvegio *solvegio.Client;db *store.Store;requests atomic.Int64;verified atomic.Int64;blocked atomic.Int64;replays atomic.Int64;invalid atomic.Int64;unknown atomic.Int64;webhooks atomic.Int64}

func main(){
 cfg:=config.Load();id,err:=qzcrypto.GenerateIdentity("qz-key-001");if err!=nil{log.Fatal(err)}
 now:=time.Now().UTC();reg:=trust.NewRegistry();reg.Put(trust.Key{Issuer:"SolveGio-Partner-Demo",KID:id.KeyID,Algorithm:"Ed25519 + ML-DSA-65",Status:"ACTIVE",Fingerprint:id.Fingerprint,ValidFrom:now,ValidUntil:now.AddDate(1,0,0),EdPublic:id.EdPublic,PQPublic:id.PQPublic})
 var rs replay.Store=replay.NewMemory();if cfg.RedisURL!=""{if r,e:=replay.NewRedis(cfg.RedisURL);e==nil&&r.Ping(context.Background())==nil{rs=r}}
 db,_:=store.New(context.Background(),cfg.DatabaseURL)
 a:=&App{cfg:cfg,audit:audit.New(),trust:reg,keys:qzcrypto.NewKeyStore(id),replay:rs,solvegio:solvegio.New(cfg.SolveGioBaseURL,cfg.SolveGioAPIKey,cfg.SolveGioTimeout),db:db}
 m:=http.NewServeMux();m.HandleFunc("/healthz",a.health);m.HandleFunc("/readyz",a.health);m.HandleFunc("/api/dashboard",a.dashboard);m.HandleFunc("/api/trust-registry",a.registry);m.HandleFunc("/api/audit-log",a.auditLog);m.HandleFunc("/api/solvegio",a.solvegioStatus);m.HandleFunc("/api/simulator",a.simulator);m.HandleFunc("/api/demo/identity",a.demoIdentity);m.HandleFunc("/gateway/forward",a.forward);m.HandleFunc("/webhooks/solvegio",a.solvegioWebhook);m.Handle("/",http.FileServer(http.Dir("./web")))
 srv:=&http.Server{Addr:":"+cfg.Port,Handler:m,ReadHeaderTimeout:5*time.Second,ReadTimeout:20*time.Second,WriteTimeout:20*time.Second,IdleTimeout:60*time.Second}
 log.Printf("QuantZen gateway listening on :%s",cfg.Port);log.Fatal(srv.ListenAndServe())
}
func(a *App)health(w http.ResponseWriter,_ *http.Request){httpx.JSON(w,200,map[string]any{"status":"ok","version":"0.1.0-mvp"})}
func(a *App)dashboard(w http.ResponseWriter,_ *http.Request){httpx.JSON(w,200,map[string]any{"protected_requests":12482+a.requests.Load(),"verified":12391+a.verified.Load(),"blocked":91+a.blocked.Load(),"replay_attacks":27+a.replays.Load(),"invalid_signatures":38+a.invalid.Load(),"unknown_keys":11+a.unknown.Load(),"webhook_events":412+a.webhooks.Load(),"events":a.audit.List()})}
func(a *App)registry(w http.ResponseWriter,_ *http.Request){httpx.JSON(w,200,a.trust.List())}
func(a *App)auditLog(w http.ResponseWriter,_ *http.Request){httpx.JSON(w,200,a.audit.List())}
func(a *App)solvegioStatus(w http.ResponseWriter,_ *http.Request){env:="DEMO";if a.solvegio.Configured(){env="SANDBOX/CONFIGURED"};httpx.JSON(w,200,map[string]any{"environment":env,"api_connection":a.solvegio.Configured(),"webhook_status":a.cfg.WebhookSecret!="","last_event":time.Now().UTC().Format("15:04:05")})}
func(a *App)demoIdentity(w http.ResponseWriter,_ *http.Request){id,_:=a.keys.Get("qz-key-001");httpx.JSON(w,200,map[string]any{"kid":id.KeyID,"ed25519_public":base64.RawURLEncoding.EncodeToString(id.EdPublic),"mldsa65_public":base64.RawURLEncoding.EncodeToString(id.PQPublic.Bytes()),"fingerprint":id.Fingerprint})}
func(a *App)signDemo(method,p string,body []byte)map[string]string{canon,err:=canonical.JSON(body);if err!=nil{return nil};now:=fmt.Sprint(time.Now().Unix());nonce:=fmt.Sprintf("nonce-%d",time.Now().UnixNano());digest:=protocol.Digest(canon);msg:=protocol.SigningString(method,p,now,nonce,digest);id,_:=a.keys.Get("qz-key-001");ed,pq,_:=qzcrypto.Sign(id,[]byte(msg));return map[string]string{"X-QZ-Version":protocol.Version,"X-QZ-Key-Id":id.KeyID,"X-QZ-Timestamp":now,"X-QZ-Nonce":nonce,"X-QZ-Content-Digest":digest,"X-QZ-Signature-Ed25519":ed,"X-QZ-Signature-MLDSA65":pq}}
func(a *App)verifyRequest(tenant string,h http.Header,body []byte,method,p string)(string,string,string){env,err:=protocol.FromHeaders(h);if err!=nil{return"400","BLOCK","INVALID_SIGNATURE"};if env.Version!=protocol.Version{return"400","BLOCK","INVALID_SIGNATURE"};canon,err:=canonical.JSON(body);if err!=nil{return"400","BLOCK","INVALID_JSON"};digest:=protocol.Digest(canon);if !strings.EqualFold(digest,env.ContentDigest){return"400","BLOCK","PAYLOAD_TAMPERED"};if time.Since(time.Unix(env.Timestamp,0)).Abs()>a.cfg.TimestampTolerance{return"401","BLOCK","EXPIRED_TIMESTAMP"};key,ok:=a.trust.Get(env.KeyID);if !ok{a.unknown.Add(1);return"401","BLOCK","UNKNOWN_KEY"};if key.Status!="ACTIVE"{return"401","BLOCK","REVOKED_KEY"};msg:=protocol.SigningString(method,p,fmt.Sprint(env.Timestamp),env.Nonce,env.ContentDigest);edOK,pqOK,err:=qzcrypto.Verify(key.EdPublic,key.PQPublic,[]byte(msg),env.Ed25519Signature,env.MLDSASignature);if err!=nil||!edOK||!pqOK{a.invalid.Add(1);return"401","BLOCK","INVALID_SIGNATURE"};claimed,err:=a.replay.Claim(context.Background(),"qz:"+tenant+":"+env.Nonce,5*time.Minute);if err!=nil||!claimed{a.replays.Add(1);return"409","BLOCK","REPLAY_DETECTED"};return"200","ALLOW","VERIFIED"}
func(a *App)forward(w http.ResponseWriter,r *http.Request){if r.Method!="POST"{httpx.Error(w,405,"POST required");return};target:=path.Clean(r.URL.Query().Get("path"));if !strings.HasPrefix(target,"/v1/"){httpx.Error(w,400,"only /v1/* paths are allowed");return};body,err:=io.ReadAll(io.LimitReader(r.Body,4<<20));if err!=nil{httpx.Error(w,400,"invalid body");return};method:=strings.ToUpper(r.URL.Query().Get("method"));if method==""{method="POST"};_,decision,detail:=a.verifyRequest(r.Header.Get("X-Tenant"),r.Header,body,method,target);if decision!="ALLOW"{httpx.Error(w,401,detail);return};start:=time.Now();code,headers,resp,err:=a.solvegio.Do(r.Context(),method,target,bytes.NewReader(body));if err!=nil{httpx.Error(w,502,err.Error());return};for k,v:=range headers{if strings.EqualFold(k,"Content-Type")&&len(v)>0{w.Header().Set(k,v[0])}};lat:=time.Since(start).Milliseconds();a.requests.Add(1);a.verified.Add(1);e:=a.audit.Add(audit.Event{Type:detail,Endpoint:target,Tenant:r.Header.Get("X-Tenant"),KeyID:r.Header.Get("X-QZ-Key-Id"),Decision:"ALLOW",LatencyMs:lat,Details:fmt.Sprintf("upstream=%d",code)});_=a.db.Insert(r.Context(),e);w.Header().Set("X-QuantZen-Decision","ALLOW");w.Header().Set("X-QuantZen-Audit-Hash",e.Hash);w.WriteHeader(code);_,_=w.Write(resp)}
func(a *App)simulator(w http.ResponseWriter,r *http.Request){if r.Method!="POST"{httpx.Error(w,405,"POST required");return};var in struct{Scenario string};_=json.NewDecoder(r.Body).Decode(&in);if in.Scenario==""{in.Scenario="valid"};start:=time.Now();body:=[]byte("{"pricing_id":"demo-pricing","buyer":{"email":"demo@example.com"}}");h:=http.Header{};for k,v:=range a.signDemo("POST","/v1/payments",body){h.Set(k,v)};switch in.Scenario{case"invalid_signature":h.Set("X-QZ-Signature-MLDSA65","bad");case"tampered_payload":body=[]byte("{"pricing_id":"tampered","buyer":{"email":"demo@example.com"}}");case"expired_timestamp":h.Set("X-QZ-Timestamp",fmt.Sprint(time.Now().Add(-10*time.Minute).Unix()));case"reused_nonce":_,_=a.replay.Claim(context.Background(),"qz:partner-demo:"+h.Get("X-QZ-Nonce"),5*time.Minute);case"revoked_key":a.trust.Revoke("qz-key-001");case"unknown_key":h.Set("X-QZ-Key-Id","unknown-key");case"duplicate_webhook":return};status,decision,detail:=a.verifyRequest("partner-demo",h,body,"POST","/v1/payments");if in.Scenario=="revoked_key"{a.trust.Activate("qz-key-001")};lat:=time.Since(start).Milliseconds();a.requests.Add(1);if decision=="ALLOW"{a.verified.Add(1)}else{a.blocked.Add(1)};e:=a.audit.Add(audit.Event{Type:detail,Endpoint:"/v1/payments",Tenant:"partner-demo",KeyID:h.Get("X-QZ-Key-Id"),Decision:decision,LatencyMs:lat,Details:status});_=a.db.Insert(r.Context(),e);httpx.JSON(w,200,map[string]any{"scenario":in.Scenario,"decision":decision,"status":status,"details":detail,"latency_ms":lat})}
func(a *App)solvegioWebhook(w http.ResponseWriter,r *http.Request){body,err:=io.ReadAll(io.LimitReader(r.Body,4<<20));if err!=nil{httpx.Error(w,400,"read error");return};a.webhooks.Add(1);if err=webhook.Verify(r,body,a.cfg.WebhookSecret,a.cfg.TimestampTolerance);err!=nil{e:=a.audit.Add(audit.Event{Type:"INVALID_WEBHOOK_SIGNATURE",Endpoint:"/webhooks/solvegio",Decision:"BLOCK",Details:err.Error()});_=a.db.Insert(r.Context(),e);httpx.Error(w,401,err.Error());return};var event struct{ID string};_=json.Unmarshal(body,&event);if event.ID!=""{claimed,e:=a.replay.Claim(r.Context(),"webhook:"+event.ID,24*time.Hour);if e!=nil||!claimed{httpx.Error(w,409,"DUPLICATE_WEBHOOK");return}};e:=a.audit.Add(audit.Event{Type:"WEBHOOK_VERIFIED",Endpoint:"/webhooks/solvegio",Decision:"ALLOW",Details:"SolveGio HMAC verified"});_=a.db.Insert(r.Context(),e);httpx.JSON(w,200,map[string]any{"ok":true,"audit_hash":e.Hash})}
