const metricSpec=[["Protected Requests","protected_requests","↗ 12%"],["Verified","verified","↗ 10%"],["Blocked","blocked","↗ 5%"],["Replay Attacks","replay_attacks","↓ 8%"],["Invalid Signatures","invalid_signatures","↗ 4%"],["Unknown Keys","unknown_keys","↓ 3%"],["Webhook Events","webhook_events","↗ 10%"]];
const scenarios=[["valid","Valid Request","Signed request"],["invalid_signature","Invalid Signature","Bad PQ signature"],["tampered_payload","Tampered Payload","Modify body after signing"],["expired_timestamp","Expired Timestamp","Old timestamp"],["reused_nonce","Reused Nonce","Reuse nonce"],["revoked_key","Revoked Key","Use revoked key"],["unknown_key","Unknown Key","Unknown kid"],["duplicate_webhook","Duplicate Webhook","Replay event"]];
async function getJSON(u,o){const r=await fetch(u,o);return r.json()}
function metrics(d){document.querySelector("#metrics").innerHTML=metricSpec.map((m,i)=>`<div class="metric"><div class="metric-top"><span class="metric-icon">${["⌁","✓","×","↻","!","⌕","↗"][i]}</span>${m[0]}</div><b>${Number(d[m[1]]).toLocaleString()}</b><small>${m[2]}</small></div>`).join("")}
function tables(events){const rows=events.slice(0,8);document.querySelector("#traffic tbody").innerHTML=rows.length?rows.map(e=>{const decision=e.Decision||e.decision,ep=e.Endpoint||e.endpoint;return `<tr><td>${new Date(e.Time||e.time).toLocaleTimeString()}</td><td>${ep==="/v1/payments"?"POST":"GET"}</td><td>${ep}</td><td>${e.Tenant||e.tenant||"partner-demo"}</td><td>${e.KeyID||e.key_id||"qz-key-001"}</td><td class="${decision==="ALLOW"?"active":"revoked"}">${decision==="ALLOW"?"✓ Valid":"× Invalid"}</td><td>${e.LatencyMs||e.latency_ms||0} ms</td><td><span class="${decision==="ALLOW"?"allow":"block"}">${decision==="ALLOW"?"ALLOWED":"BLOCKED"}</span></td></tr>`}).join(""):`<tr><td colspan="8">No live traffic yet. Use Simulator.</td></tr>`;const types=["INVALID_SIGNATURE","REPLAY_DETECTED","EXPIRED_TIMESTAMP","UNKNOWN_KEY","PAYLOAD_TAMPERED","REVOKED_KEY"];document.querySelector("#events tbody").innerHTML=types.map(t=>`<tr><td>—</td><td style="color:#e64747">${t}</td><td>Gateway security control</td><td><span class="${t==="EXPIRED_TIMESTAMP"?"warn":"block"}">${t==="EXPIRED_TIMESTAMP"?"Medium":"High"}</span></td></tr>`).join("")}
function trust(keys){document.querySelector("#trust").innerHTML=keys.map(k=>`<tr><td>${k.Issuer}</td><td>${k.KID}</td><td>${k.Algorithm}</td><td><span class="${k.Status==="ACTIVE"?"active":"revoked"}">${k.Status}</span></td><td>${k.Fingerprint}</td><td>${new Date(k.ValidFrom).toISOString().slice(0,10)} → ${new Date(k.ValidUntil).toISOString().slice(0,10)}</td><td>↻ 🗑</td></tr>`).join("")}
function simulator(){document.querySelector("#sim").innerHTML=`<div class="scenario-grid">${scenarios.map(s=>`<button class="scenario" data-s="${s[0]}"><strong>${s[1]}</strong><span>${s[2]}</span></button>`).join("")}</div>`;document.querySelectorAll(".scenario").forEach(b=>b.onclick=async()=>{const r=await getJSON("/api/simulator",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({Scenario:b.dataset.s})});b.querySelector("span").textContent=`${r.decision} · ${r.details}`;load()})}
function chart(){const c=document.querySelector("#chart"),ctx=c.getContext("2d"),w=c.clientWidth,h=190;c.width=w*2;c.height=h*2;ctx.scale(2,2);ctx.strokeStyle="#dce6f5";for(let y=20;y<170;y+=30){ctx.beginPath();ctx.moveTo(20,y);ctx.lineTo(w-16,y);ctx.stroke()}for(const z of [["#0b72ff",26,95],["#ef4444",6,152]]){ctx.strokeStyle=z[0];ctx.lineWidth=2;ctx.beginPath();for(let x=20;x<w-16;x+=18){const y=z[2]+Math.sin(x/35)*z[1];x===20?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.stroke()}}
async function load(){const [d,k,s]=await Promise.all([getJSON("/api/dashboard"),getJSON("/api/trust-registry"),getJSON("/api/solvegio")]);metrics(d);tables(d.events||[]);trust(k);document.querySelector("#env").textContent=s.environment;document.querySelector("#statusEvent").textContent=s.last_event;document.querySelector("#lastEvent").textContent=s.last_event;document.querySelector("#conn").textContent=s.api_connection?"SolveGio Connected":"SolveGio Demo";chart()}
simulator();load();setInterval(load,8000);
